In [7]:
#-------------------------------------------------------------------------------
# Name:        Python sample historic data client
# Author:      Jan Grimmer
# Created:     20.03.2018
#-------------------------------------------------------------------------------

from http.client import HTTPSConnection
from base64 import b64encode
import json
import pandas as pd

HOST_STAGING = "sc-hackathon-s.urbanpulse.de"
HOST_PRODUCTION = "sc-hackathon.urbanpulse.de"
PORT_HISTORIC_DATA = 42000

USER_PW = b"hackathon:L33333t+"

def connect(host, sid, since, until):
        server = host + ":" + str(PORT_HISTORIC_DATA)

        pathTemplate = "/UrbanPulseData/historic/sensordata?since={0}&until={1}&sid={2}"
        path = pathTemplate.format(since,until,sid)

        connection = HTTPSConnection(server)
        userAndPass = b64encode(USER_PW).decode("ascii")
        headers = { 'Authorization' : 'Basic %s' %  userAndPass }

        connection.request('GET', path, headers=headers)
        response = connection.getresponse()
        data = response.read()
        return data

def get_data():
    host = HOST_STAGING
    # A list of all sensors can be obtained from https://<HOST>/UrbanPulseManagement/api/sensors with credentials hackathon/L33333t+
    sid = "846e9b95-a9b4-4d5f-b549-f6e211b9c3ba"
    since = "2018-03-26T11:18:00.000Z"
    until = "2018-03-26T11:22:00.000Z"

    data = connect(host, sid, since, until)

    wrapped_json_object = json.loads(data)
    json_array = wrapped_json_object['sensordata']
    for event in json_array[:10]:
        print("Received: " + json.dumps(event)[:100])
    return json_array

df = pd.DataFrame(get_data())
df.head(3)

Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "G", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "A", "S24": "", "S01": "R", "S23": "", "S04":
Received: {"D49-64": 0, "S20": "", "S22": "", "S21": "", "S02": "A", "S24": "", "S01": "R", "S23": "", "S04":

,Bezeichnung,D01-16,D17-32,D33-48,D49-64,Datum,Programm,S01,S02,S03,...,S31,S32,SID,Status,Uhrzeit,Uhrzeit ms,Umlaufsekunde,eventType,statementName,timestamp
0,A200,0,0,0,0,26.03.2018,12,R,G,R,...,,,846e9b95-a9b4-4d5f-b549-f6e211b9c3ba,0,13:17:58,811,730,SwarcoTMSEventType,ConnectedSignals_hackathon,2018-03-26T11:18:00.193Z
1,A200,0,0,0,0,26.03.2018,12,R,G,R,...,,,846e9b95-a9b4-4d5f-b549-f6e211b9c3ba,0,13:17:59,812,740,SwarcoTMSEventType,ConnectedSignals_hackathon,2018-03-26T11:18:01.213Z
2,A200,0,0,0,0,26.03.2018,12,R,G,R,...,,,846e9b95-a9b4-4d5f-b549-f6e211b9c3ba,0,13:18:00,812,750,SwarcoTMSEventType,ConnectedSignals_hackathon,2018-03-26T11:18:02.162Z

In [8]:
#!pip install WazeRouteCalculator
import WazeRouteCalculator

from_address = 'Köln, Germany'
to_address = 'Bad Hersfeld, Germany'
region = 'EU'
route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address, region)
route.calc_route_info(real_time=False)

From: Köln, Germany - to: Bad Hersfeld, Germany
Time 160.95 minutes, distance 252.16 km.

(160.95, 252.156)

In [16]:
import json
import pandas as pd
import requests
from pandas.io.json import json_normalize

urban_pulse_user = 'hackathon'
urban_pulse_password = 'L33333t+'
urban_pulse_url = 'https://sc-hackathon.urbanpulse.de/UrbanPulseManagement/api/'

pd.set_option('max_colwidth', 800)

In [24]:
response = requests.get(urban_pulse_url+ 'eventtypes', auth=(urban_pulse_user,urban_pulse_password), stream=True)
df = pd.DataFrame(response.json()['eventtypes']);
df.head(3).style

In [25]:
response = requests.get(urban_pulse_url +'sensors', auth=(urban_pulse_user,urban_pulse_password), stream=True)
df = pd.DataFrame(response.json()['sensors']);
df.head(3)

,categories,description,eventtype,id,location,senderid
0,[b537e6ab-ae6f-4b64-b9e6-4ed189a27665],{'reference': {'Bezeichnung': 'A 99'}},6f7d208c-6258-421c-968d-49b39495465f,138,{'type': 'undefined'},3825d55c-61fd-4924-b9e0-c49bd35aab97
1,[f8deb6ed-0ae4-4af2-8c18-3ba16e56a7c3],{'reference': {'originSID': '138'}},74b65db1-df5f-45d5-9e71-97a7c68666ba,138AN,{'type': 'undefined'},3825d55c-61fd-4924-b9e0-c49bd35aab97
2,[b537e6ab-ae6f-4b64-b9e6-4ed189a27665],{'reference': {'Bezeichnung': 'A 7'}},6f7d208c-6258-421c-968d-49b39495465f,141,{'type': 'undefined'},3825d55c-61fd-4924-b9e0-c49bd35aab97